export const JOB_CATEGORIES = [
  "Limpeza de casas",
  "Limpeza de escritórios",
  "Lavagem de carros",
  "Entrega de encomendas",
  "Motoboy / estafeta",
  "Montagem de móveis",
  "Reparação de móveis",
  "Pintura de casas",
  "Pequenos trabalhos de construção",
  "Ajuda em mudanças",
  "Jardinagem",
  "Corte de relva",
  "Limpeza de quintal",
  "Babysitting",
  "Apoio escolar (explicador)",
  "Aulas de inglês",
  "Aulas de matemática",
  "Aulas de informática",
  "Fotografia de eventos",
  "Edição de vídeo",
  "Criação de logotipos",
  "Design gráfico simples",
  "Gestão de redes sociais",
  "Publicação de posts",
  "Criação de conteúdos TikTok",
  "Marketing digital básico",
  "Venda de produtos online",
  "Assistente virtual",
  "Digitação de documentos",
  "Tradução simples",
  "Reparação de telemóveis",
  "Instalação de apps",
  "Configuração de Wi-Fi",
  "Reparação de computadores",
  "Formatação de PCs",
  "Instalação de Windows",
  "Suporte técnico básico",
  "Venda de peças eletrónicas",
  "Instalação de câmeras de segurança",
  "Reparação de eletrodomésticos",
  "Culinária (cozinhar em casa do cliente)",
  "Venda de comida caseira",
  "Catering pequeno evento",
  "Organização de festas",
  "Decoração de eventos",
  "Limpeza pós-festa",
  "Segurança privada informal",
  "Auxiliar de loja",
  "Repositor de stock",
  "Atendimento em eventos"
];
